import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

function LandingScreen({
  createGame,
  joinGame,
  gameIdInput,
  setGameIdInput,
  userName,
  setUserName,
}) {

  //some of the css are generated by gemini ai for the purpose of learning tailwind css | redone by tony
  return (
    <div className="fixed inset-0 flex items-center justify-center bg-white">
      <div className="flex flex-col gap-3 p-3 ">
        
         <h1 className="pb-5 text-7xl font-bold text-center">
        QuizRace
        </h1>

        <div className="flex items-center gap-3 w-full max-w-xl">

        <input
          type="text"
          placeholder="Your Name"
          className="flex-1 p-2 rounded-lg border-none bg-gray-500 text-white placeholder-gray-100"
          value={userName}
          onChange={(e) => setUserName(e.target.value)}
        ></input>

        <button 
          onClick={createGame} 
          disabled={!userName} 
          className="flex-1 p-2 px-4 rounded-lg bg-red-500 text-white font-semibold transition-transform transform hover:scale-105 disabled:opacity-50"
          >
            Host New Game
          </button>
        </div>
      
      <div className="flex items-center gap-3 w-full max-w-xl">

        <input
        type="text"
        placeholder="Enter Game ID to Join"
        className="flex-1 p-2 rounded-lg border-none bg-gray-500 text-white placeholder-gray-100"
        value={gameIdInput}
        onChange={(e) => setGameIdInput(e.target.value)}
      ></input>
      
      <button
        onClick={joinGame}
        disabled={!(gameIdInput && gameIdInput.length == 6 && userName)}
        className="flex-1 p-2 px-4 rounded-lg bg-blue-500 text-white font-semibold transition-transform transform hover:scale-105  disabled:opacity-50">
        Join Game
      </button>
      </div>

      </div>
    </div>
  );
}

export default LandingScreen;
